# 1. DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://db.znujbhxbddjsygubblsb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. LOGGING
logging.level.org.springframework=INFO
logging.level.com.example.QLNH_BTL=DEBUG

# 4. DEPLOY CONFIGURATION
spring.main.headless=true
server.tomcat.max-http-form-post-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ntruonggiang180606@gmail.com
spring.mail.password=kfszxhulvwcmnoqh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com